name: "CI"

on: push

jobs:
  build:
    name: "Gradle build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: "Set up JDK 11"
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: "Build with Gradle"
        # TODO Replace with `build` to include integration tests, once we figure out a way to set up TeX CI.
        run: "./gradlew assemble"
