name: Gradle CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: docker.pkg.github.com/reimersoftware/tex-docker/miktex-on-the-fly:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: Set up JDK 1.8
        run: |
          apt-get update
          apt-get install -y --no-install-recommends openjdk-8-jdk
          rm -rf /var/lib/apt/lists/*
      - name: Build with Gradle
        run: ./gradlew build
